model_name: 'Pointnet'
lr: 0.001
lr_decay: 0.5
lr_step: 20
lr_clip: 0.000001
feat_reg_eff: 0.001
btch_momentum: 0.5
btch_max_epoch: 100
l2coef: 0.0000001
batch_size: 10
epochs: 300
epoch_start: 0
input_size: 2048
weight_adapt: 1

valid_per: 0.2
test_per: 0.1
augmentation: False
device: 'cuda'
valid_freq: 3
stop_counter: 10
save_model: False
save_path: './results/'
train_data: './datasets/JRDB/test_data.h5py'
valid_data: './datasets/JRDB/test_data.h5py'
test_data: './datasets/JRDB/test_data.h5py'
init_weights: null
session_name: 'v01.04'
online: False
visualization: False
