lr: 0.001
lr_decay: 0.5
lr_step: 20
lr_clip: 0.000001
feat_reg_eff: 0.001
btch_momentum: 0.5
btch_max_epoch: 100
l2coef: 0.0000001
batch_size: 32
epochs: 300
epoch_start: 9
input_size: 2048

valid_per: 0.2
test_per: 0.1
device: 'cuda'
valid_freq: 1
stop_counter: 20
save_model: True
save_path: './results/'
data_root_path: '/media/visitor1/DBStorage/Datasets/JRDB/training_format/training_data.h5py'
init_weights: null
session_name: 'v00.01'
online: False
visualization: True
